### ISSUE TITLE
cannot import roughjs 3.0.0 via require('roughjs')

### ISSUE THREAD

**Issue by jedierikb** [pshihn/rough#100]
`const rough = require('roughjs');`
works with 2.2.5
but with 3.0.0 console.log on rough just gives `{}`

**Comment by pshihn** [comment]
try importing from `roughjs/dist/rough.umd`
your config may not be picking up the correct umd module

**Comment by jedierikb** [comment]
going to claim package.json ignorance on this one... where in _my_ package.json do I specify I want your 'main' value instead of 'browser' value (which is what I seem to be loading?)  

Or is this preference made in node or elsewhere?  I suspect the answer is idiosyncratic to my setup (e.g. gulp, etc.) but guidance appreciated.

**Comment by jedierikb** [comment]
Got it to work.
Here is a simple gulp file which can load roughjs:
https://gist.github.com/jedierikb/af89ef657cdcaf7a4ee3a34b23ea35c8

In your es6 code, 
```
	const rough = require( 'roughjs/dist/rough.umd.js' );
	console.error( 'rough', rough );
```

**Comment by beizhedenglong** [comment]
I have the same problem with parcel bundler

**Comment by pshihn** [comment]
@beizhedenglong  try importing from 'roughjs/dist/rough.umd.js'

**Comment by jwilber** [comment]
@pshihn is there a change on this for v4? I'm trying to update roughViz to `roughjs@v4` but it's throwing a `_roughjs.default.svg is not a function` error. Haven't had too much time to dig into it yet so figured I'd just ask here real quick.

**Comment by honkskillet** [comment]
It doesn't seem like the import knows where to look.  There is no dist file.

**Comment by pshihn** [comment]
See https://github.com/pshihn/rough/issues/130

**Comment by guimeisang** [comment]
V4.3.1
import rough from 'roughjs/bundled/rough.esm.js'
